from typing import Any, AsyncContextManager, Protocol

class WebSocketClientProtocol(Protocol):
    open: bool
    async def send(self, data: str) -> Any: ...
    async def recv(self) -> Any: ...
    async def ping(self) -> Any: ...

class ConnectionClosed(Exception): ...

class exceptions:
    ConnectionClosed: type = ConnectionClosed

async def connect(
    url: str, *args: Any, **kwargs: Any
) -> AsyncContextManager[WebSocketClientProtocol]: ...
