from typing import Any, Dict, Optional

class Response:
    text: str
    status_code: int
    def json(self) -> Any: ...
    def raise_for_status(self) -> None: ...


class RequestException(Exception): ...


class Timeout(RequestException): ...

class Session:
    headers: dict[str, str]
    def __init__(self) -> None: ...
    def request(self, method: str, url: str, json: Any | None = None, timeout: float | None = None) -> Response: ...
    def get(self, url: str, **kwargs: Any) -> Response: ...
    def post(self, url: str, **kwargs: Any) -> Response: ...

class HTTPError(RequestException):
    response: Response | None


def get(url: str, **kwargs: Any) -> Response: ...

def post(url: str, **kwargs: Any) -> Response: ...
