from typing import Any, Iterable, List

class _BoolIndex:
    def __invert__(self) -> List[bool]: ...
    def __iter__(self) -> Any: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Any) -> bool: ...

class _Index:
    def duplicated(self, keep: str = ...) -> _BoolIndex: ...
    def __ge__(self, other: Any) -> _BoolIndex: ...

class DataFrame:
    index: _Index
    def __init__(self, data: Any = ...) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Any) -> "DataFrame": ...
    def set_index(self, key: str) -> "DataFrame": ...
    def to_parquet(self, path: Any, *args: Any, **kwargs: Any) -> None: ...
    def sort_index(self) -> "DataFrame": ...
    def tail(self, n: int) -> "DataFrame": ...
    def reset_index(self) -> "DataFrame": ...
    def to_dict(self, orient: str = ...) -> Any: ...



class Series:
    pass

def read_parquet(path: Any, *args: Any, **kwargs: Any) -> DataFrame: ...

def concat(objs: Iterable[DataFrame], *args: Any, **kwargs: Any) -> DataFrame: ...
